### ISSUE TITLE
是否需要建立一个微信交流群

### ISSUE THREAD

**Issue by miss-mumu** [miss-mumu/developer2gwy#20]
自项目开始到现在，我们初步统计了一下，有大概10个左右的朋友，会询问是否有微信交流群，想要加群。对此，我们统一的回复是：暂时没有建群的想法。
因为公考是一个比较个人的事情，无论是备考，还是问题，都极具个性化。而且，群里面的信息质量参差不齐，我们不希望群信息打扰到大家备考。

但，也需要承认群的正面作用，每个人都有各自的信息源，我们的信息也能够直达群里面每一个人。而且群里面的每一个人也可以互帮互助，相互监督，相互促进，相互学习。

因此，我们决定开这个issue，看大家有什么想法没，我们会结合大家的想法、意见、建议。决定是否需要一个交流分享群。

问题点：
- 你是否支持建立一个交流群
- 群里面你希望有些什么信息：岗位数据、备考资料、考试心得等等

**Comment by Nikola-T-Hi** [comment]
支持

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by renshuwei** [comment]
支持

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by renshuwei** [comment]
支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 上午8:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [miss-mumu/developer2gwy] 是否需要建立一个微信交流群 (Issue #20)




  
支持
  
感谢回复

**Comment by bashehacker** [comment]
支持

**Comment by miss-mumu** [comment]
> 支持
感谢回复

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by CPC-Coder** [comment]
支持

**Comment by lvduidui** [comment]
支持

**Comment by Stars-Night** [comment]
支持

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by miss-mumu** [comment]
> 支持

感谢回复

**Comment by huangsiyuan2015** [comment]
支持

**Comment by PLAmao** [comment]
支持

**Comment by miss-mumu** [comment]
> 支持
感谢回复

**Comment by zylbiubiubiu** [comment]
支持，什么时候建群？

**Comment by miss-mumu** [comment]
> 支持，什么时候建群？

五一过后，会建群。感谢回复

**Comment by z-jt-best** [comment]
支持

**Comment by CruiseShao** [comment]
> > 支持，什么时候建群？
> 
> 五一过后，会建群。感谢回复

建群后求拉~~~

**Comment by Lokep** [comment]
微信群求拉😭

**Comment by moreshuang** [comment]
不支持建立群聊，多数人进入群聊只是为了获取信息，由于群聊的交流方式是即时性的，这会在重复的问答中造成资源浪费、磨灭贡献者的热情。需要任何信息，都可以在github或者公考社区自行检索。有任何疑问，也都可以发帖求助；每个人都应当能够独立完整地表达自己的想法，而不是只能在对话中逐渐表达。
