### ISSUE TITLE
行测 申论 共基 职测 综应 分别对应什么

### ISSUE THREAD

**Issue by CPC-Coder** [miss-mumu/developer2gwy#23]
行测 申论 共基 职测 综应 分别对应什么
这块我一直比较混淆

**Comment by CPC-Coder** [comment]
我打算自己先看下 再报班  但是学什么一直被混淆着

30岁以后,可以选择的岗位不多诶

**Comment by miss-mumu** [comment]
行测：行政职业能力测验，由130道选择题组成，主要考察常识、言语理解、数量关系、逻辑推理、资料分析。
申论：类似语文的阅读理解+作文。通过写作考察阅读理解能力、文字表达能力、综合分析能力、提出问题和解决问题能力等。
行测与申论是省考、国考必考科目。

共基：公共基础知识，主要考察政治、经济、法律、人文、历史、科技、行政、公文写作、时事政治等。主要在是三支一扶、事业单位、军转干等考试中考察，可以理解为2.0版本的行测常识。

职测：行政职业能力测验，事业单位招考中常考，但根据所报岗位不同，有分类。可以通俗理解为简版的行测。
综应：综合应用能力，事业单位招考中常考，也是根据所报岗位不同，有一定的侧重点。可以通俗理解为更具应用性的申论。
职测、综应是事业单位招考中常考的，有的地方，会将共基柔和在一起考。

难度：
国考行测>省考行测>职测>共基
国考申论>省考申论>综应

建议添加我们的联系方式，我们免费分享一些课程你，你可以先熟悉熟悉。

---

30岁，还是有很多机会的，上述考试，每年最少能够考3次，如果还有补招，至少4次。大多考试限制35岁，那么，还有20次机会左右。而你只需要考好一次，只需要一次，就可以朝九晚五、左牵黄右擎苍。

**Comment by CPC-Coder** [comment]
怎么加
