### ISSUE TITLE
【重要】关于2023年度公考资源购买进度公示

### ISSUE THREAD

**Issue by miss-mumu** [miss-mumu/developer2gwy#28]
2023年度的公考资料，由于捐赠一直达不到购买全部课程资料的门槛。所以一直迟迟没有落实，再次，向大家道歉！

我们收到部分捐赠朋友，以及大部分添加联系方式朋友的反馈，对于2023年度最新课程资料是有急迫的需求。我们与吴凡、以及相关的朋友进行多次沟通。可以分批分期的购买最新资料。

因此，这里需要大家评论反馈如下两个问题：
- **是否支持动用捐赠购买课程资料**
- **优先购买哪些课程材料**

最新课程材料有：

<img src="https://gitee.com/miss-mu-mu/developer2gwy/raw/main/img/1.png" width="30%">

<img src="https://gitee.com/miss-mu-mu/developer2gwy/raw/main/img/2.png" width="30%">

<img src="https://gitee.com/miss-mu-mu/developer2gwy/raw/main/img/3.png" width="30%">

<img src="https://gitee.com/miss-mu-mu/developer2gwy/raw/main/img/4.png" width="30%">

<img src="https://gitee.com/miss-mu-mu/developer2gwy/raw/main/img/5.png" width="30%">

**Comment by zhaoyoushuai** [comment]
绝对支持使用捐赠购买课程资料🕊
