### ISSUE TITLE
感谢前辈提供的宝贵经验，希望还能看到这个项目继续更新！

### ISSUE THREAD

**Issue by YUNYE01** [miss-mumu/developer2gwy#51]
2023年末才开始明白普通人在互联网行业的局限，当初满怀信心前往杭州的初创公司，从2020年初实习开始便享受到996福报的威力，拿着微薄的薪水，望着看不到尽头的房价，稚嫩时还幻想着能在这里扎根……

对社会的无知导致一路遭遇各种毒打，直到看到前辈们卷出了另一条血路“考公考编”！这是我从未了解过的职业，新的认知仿佛宇宙爆炸一般，一语惊醒梦中人不为过！前辈们无私奉献的经验，无比宝贵珍重！感谢你们！

未来的路大概率也会朝着前辈们的方向前进，希望前辈们有机会常回来 developer2gwy 看看！祝每位前辈工作顺利、家庭美满、幸福健康！！！

**Comment by nchu-student-6** [comment]
1
